"""Generate, write, and clean up the temporary provider override file.

The override file points the google provider at localgcp endpoints and supplies
a dummy ``access_token`` so the provider skips Google credential discovery.
"""

from __future__ import annotations

import os
from collections.abc import Iterable

from .endpoints import build_endpoints

# Name of the temporary override file written into each Terraform directory.
OVERRIDE_FILENAME = "localgcp_providers_override.tf"

# Dummy OAuth token: any non-empty value bypasses ADC / credential lookup.
DUMMY_ACCESS_TOKEN = "localgcp-dummy-token"

_HEADER = (
    "# Generated by tflocal-gcp. Do not edit or commit; removed after each run.\n"
)


def _render_provider(provider: dict, endpoints: dict[str, str]) -> str:
    """Render a single ``provider`` override block."""
    lines = [f'provider "{provider["type"]}" {{']
    if provider.get("alias"):
        lines.append(f'  alias        = "{provider["alias"]}"')
    lines.append(f'  access_token = "{DUMMY_ACCESS_TOKEN}"')
    for attr in sorted(endpoints):
        lines.append(f'  {attr} = "{endpoints[attr]}"')
    lines.append("}")
    return "\n".join(lines)


def generate_override_content(
    providers: list[dict],
    host: str = "localhost",
) -> str:
    """Render the HCL contents of the override file for the given providers.

    Each ``{"type", "alias"}`` entry becomes a ``provider`` block carrying a
    dummy ``access_token`` and every supported ``<service>_custom_endpoint``.
    """
    endpoints = build_endpoints(host)
    blocks = [_render_provider(p, endpoints) for p in providers]
    return _HEADER + "\n\n".join(blocks) + "\n"


def write_override_file(directory: str, content: str) -> str:
    """Write ``content`` to the override file in ``directory``; return its path."""
    path = os.path.join(directory, OVERRIDE_FILENAME)
    with open(path, "w", encoding="utf-8") as fp:
        fp.write(content)
    return path


def cleanup_override_files(paths: Iterable[str]) -> None:
    """Delete previously written override files, ignoring missing ones."""
    for path in paths:
        try:
            os.remove(path)
        except FileNotFoundError:
            pass
        except OSError as exc:  # pragma: no cover - best-effort cleanup
            print(f"Warning: could not remove '{path}': {exc}. Delete it manually.")
